# Site settings
title: "blaze - designer"
description: "product design / digital experiments"
author: "blaze"
url: ""
baseurl: ""

# Build settings
source: .
destination: ./_site
include: ['.htaccess']
exclude: ['Gemfile', 'Gemfile.lock', 'node_modules', '.git', '.gitignore', 'includes']
keep_files: []

# Plugins
plugins:
  - jekyll-seo-tag

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Markdown
highlighter: rouge
markdown: kramdown

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed
